# Generated by Django 4.2.9 on 2024-02-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traffic",
            name="key",
        ),
        migrations.AlterField(
            model_name="traffic",
            name="amende",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="traffic",
            name="classe",
            field=models.CharField(max_length=20),
        ),
    ]
