# Generated by Django 4.2.9 on 2024-02-16 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_remove_traffic_key_alter_traffic_amende_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Traffic",
            new_name="Amendes",
        ),
        migrations.RenameField(
            model_name="amendes",
            old_name="amende",
            new_name="category",
        ),
    ]
